<h2>Photos from the Autumn 2009 Event</h2>
<div class="highslide-gallery" style="width: 600px; margin: auto">
	<a class="highslide" href="media/images/photos/autumn_2009/p1010722.jpg" onclick="return hs.expand(this)">
		<img src="media/images/photos/autumn_2009/p1010722_thumb.jpg" alt="" /></a>
	<a class="highslide" href="media/images/photos/autumn_2009/p1010723.jpg" onclick="return hs.expand(this)">
		<img src="media/images/photos/autumn_2009/p1010723_thumb.jpg" alt="" /></a>
	<a class="highslide" href="media/images/photos/autumn_2009/p1010724.jpg" onclick="return hs.expand(this)">
		<img src="media/images/photos/autumn_2009/p1010724_thumb.jpg" alt="" /></a>
	<a class="highslide" href="media/images/photos/autumn_2009/p1010725.jpg" onclick="return hs.expand(this)">
		<img src="media/images/photos/autumn_2009/p1010725_thumb.jpg" alt="" /></a>
	<a class="highslide" href="media/images/photos/autumn_2009/p1010726.jpg" onclick="return hs.expand(this)">
		<img src="media/images/photos/autumn_2009/p1010726_thumb.jpg" alt="" /></a>
	<a class="highslide" href="media/images/photos/autumn_2009/p1010727.jpg" onclick="return hs.expand(this)">
		<img src="media/images/photos/autumn_2009/p1010727_thumb.jpg" alt="" /></a>
	<a class="highslide" href="media/images/photos/autumn_2009/p1010728.jpg" onclick="return hs.expand(this)">
		<img src="media/images/photos/autumn_2009/p1010728_thumb.jpg" alt="" /></a>
	<a class="highslide" href="media/images/photos/autumn_2009/p1010729.jpg" onclick="return hs.expand(this)">
		<img src="media/images/photos/autumn_2009/p1010729_thumb.jpg" alt="" /></a>
	<a class="highslide" href="media/images/photos/autumn_2009/p1010730.jpg" onclick="return hs.expand(this)">
		<img src="media/images/photos/autumn_2009/p1010730_thumb.jpg" alt="" /></a>
	<a class="highslide" href="media/images/photos/autumn_2009/p1010731.jpg" onclick="return hs.expand(this)">
		<img src="media/images/photos/autumn_2009/p1010731_thumb.jpg" alt="" /></a>
	<a class="highslide" href="media/images/photos/autumn_2009/p1010732.jpg" onclick="return hs.expand(this)">
		<img src="media/images/photos/autumn_2009/p1010732_thumb.jpg" alt="" /></a>
	<a class="highslide" href="media/images/photos/autumn_2009/p1010733.jpg" onclick="return hs.expand(this)">
		<img src="media/images/photos/autumn_2009/p1010733_thumb.jpg" alt="" /></a>
	<a class="highslide" href="media/images/photos/autumn_2009/p1010734.jpg" onclick="return hs.expand(this)">
		<img src="media/images/photos/autumn_2009/p1010734_thumb.jpg" alt="" /></a>
	<a class="highslide" href="media/images/photos/autumn_2009/p1010735.jpg" onclick="return hs.expand(this)">
		<img src="media/images/photos/autumn_2009/p1010735_thumb.jpg" alt="" /></a>
	<a class="highslide" href="media/images/photos/autumn_2009/p1010736.jpg" onclick="return hs.expand(this)">
		<img src="media/images/photos/autumn_2009/p1010736_thumb.jpg" alt="" /></a>
	<a class="highslide" href="media/images/photos/autumn_2009/p1010737.jpg" onclick="return hs.expand(this)">
		<img src="media/images/photos/autumn_2009/p1010737_thumb.jpg" alt="" /></a>
</div>