<h2>Photos from the Spring 2010 Event</h2>
<p>Not the best quality, but there you go, if you have anymore, let me know.</p>
<div class="highslide-gallery" style="width: 600px; margin: auto">
	<a class="highslide" href="media/images/photos/spring_2010/p1020235.jpg" onclick="return hs.expand(this)">
		<img src="media/images/photos/spring_2010/p1020235_thumb.jpg" alt="???" /></a>
	<a class="highslide" href="media/images/photos/spring_2010/p1020236.jpg" onclick="return hs.expand(this)">
		<img src="media/images/photos/spring_2010/p1020236_thumb.jpg" alt="???" /></a>
	<a class="highslide" href="media/images/photos/spring_2010/p1020237.jpg" onclick="return hs.expand(this)">
		<img src="media/images/photos/spring_2010/p1020237_thumb.jpg" alt="???" /></a>
	<a class="highslide" href="media/images/photos/spring_2010/p1020238.jpg" onclick="return hs.expand(this)">
		<img src="media/images/photos/spring_2010/p1020238_thumb.jpg" alt="???" /></a>
	<a class="highslide" href="media/images/photos/spring_2010/p1020239.jpg" onclick="return hs.expand(this)">
		<img src="media/images/photos/spring_2010/p1020239_thumb.jpg" alt="???" /></a>
	<a class="highslide" href="media/images/photos/spring_2010/p1020240.jpg" onclick="return hs.expand(this)">
		<img src="media/images/photos/spring_2010/p1020240_thumb.jpg" alt="G???" /></a>
	<a class="highslide" href="media/images/photos/spring_2010/p1020241.jpg" onclick="return hs.expand(this)">
		<img src="media/images/photos/spring_2010/p1020240_thumb.jpg" alt="???" /></a>
	<a class="highslide" href="media/images/photos/spring_2010/p1020242.jpg" onclick="return hs.expand(this)">
		<img src="media/images/photos/spring_2010/p1020242_thumb.jpg" alt="???" /></a>
	<a class="highslide" href="media/images/photos/spring_2010/p1020243.jpg" onclick="return hs.expand(this)">
		<img src="media/images/photos/spring_2010/p1020243_thumb.jpg" alt="???" /></a>
	<a class="highslide" href="media/images/photos/spring_2010/p1020244.jpg" onclick="return hs.expand(this)">
		<img src="media/images/photos/spring_2010/p1020244_thumb.jpg" alt="???" /></a>
	<a class="highslide" href="media/images/photos/spring_2010/gordon_longest_drive.jpg" onclick="return hs.expand(this)">
		<img src="media/images/photos/spring_2010/gordon_longest_drive_thumb.jpg" alt="Gordon collects the longest drive trophy for the second time" /></a>
	<a class="highslide" href="media/images/photos/spring_2010/gordon_putting.jpg" onclick="return hs.expand(this)">
		<img src="media/images/photos/spring_2010/gordon_putting_thumb.jpg" alt="Getting the afternoon off to a good start?" /></a>
	<a class="highslide" href="media/images/photos/spring_2010/gordon_stuck_ball.jpg" onclick="return hs.expand(this)">
		<img src="media/images/photos/spring_2010/gordon_stuck_ball_thumb.jpg" alt="Hmmm, I need Bernhard Langer for this one!" /></a>
	<a class="highslide" href="media/images/photos/spring_2010/iain_nearest_pin.jpg" onclick="return hs.expand(this)">
		<img src="media/images/photos/spring_2010/iain_nearest_pin_thumb.jpg" alt="Deadeye Iain walks away with the nearest the pin trophy" /></a>
	<a class="highslide" href="media/images/photos/spring_2010/liam_approach_pose.jpg" onclick="return hs.expand(this)">
		<img src="media/images/photos/spring_2010/liam_approach_pose_thumb.jpg" alt="Posing, happy, pissed off with golf? Who knows!" /></a>
	<a class="highslide" href="media/images/photos/spring_2010/liam_putting.jpg" onclick="return hs.expand(this)">
		<img src="media/images/photos/spring_2010/liam_putting_thumb.jpg" alt="Let's see if we can get this round going!" /></a>
	<a class="highslide" href="media/images/photos/spring_2010/mike_trophy.jpg" onclick="return hs.expand(this)">
		<img src="media/images/photos/spring_2010/mike_trophy_thumb.jpg" alt="Do you think he's a bit pleased?" /></a>
	<a class="highslide" href="media/images/photos/spring_2010/the_winners.jpg" onclick="return hs.expand(this)">
		<img src="media/images/photos/spring_2010/the_winners_thumb.jpg" alt="Champions for the day" /></a>
</div>