<div id="score_tabs">
	<ul>
		<li><a href="#morning_tab">Morning</a></li>
		<li><a href="#afternoon_tab">Afternoon</a></li>
	</ul>
	<div id="morning_tab">
		<div class="scores">
			<table class="player">
				<thead>
					<tr>
						<th>Competition</th>
						<th>Player</th>
						<th>Handicap</th>
						<th class="courseinfo">Par</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>Yellow Ball</td>
						<td>Phil Reeve</td>
						<td>17</td>
						<td class="courseinfo">36</td>
					</tr>
				</tbody>
			</table>
			<table class="amscores">
				<caption>Morning</caption>
				<colgroup class="holeinfo">
					<col />
					<col />
					<col />
				</colgroup>
				<colgroup class="scoreinfo">
					<col />
					<col />
					<col />
					<col />
					<col />
					<col />
				</colgroup>
				<thead>
					<tr class="coltitles">
						<th scope="col">Hole</th>
						<th scope="col">Par</th>
						<th scope="col">SI</th>
						<th scope="col">Gross Score</th>
						<th scope="col">Gross Points</th>
						<th scope="col">Net Score</th>
						<th scope="col">Net Points</th>
						<th scope="col">Yellow Ball</th>
						<th scope="col">Yellow Ball Points</th>
					</tr>
				</thead>
				<tfoot>
					<tr>
						<td>-</td><td>36</td><td>-</td><td>45 (+9)</td><td>12</td><td>37 (+1)</td><td>18</td><td>3</td><td>26</td>
					</tr>
				</tfoot>
				<tbody>
					<tr>
						<td>1</td><td>4</td><td>9</td><td class="bogey">5</td><td>1</td><td class="par">4</td><td>2</td><td>Y</td><td>4</td>
					</tr>
					<tr>
						<td>2</td><td>4</td><td>11</td><td class="dblbogey">6</td><td>-</td><td class="bogey">5</td><td>1</td><td>N</td><td>1</td>
					</tr>
					<tr>
						<td>3</td><td>3</td><td>17</td><td class="bogey">4</td><td>1</td><td class="par">3</td><td>2</td><td>N</td><td>2</td>
					</tr>
					<tr>
						<td>4</td><td>5</td><td>3</td><td class="par">5</td><td>2</td><td class="birdie">4</td><td>3</td><td>Y</td><td>6</td>
					</tr>
					<tr>
						<td>5</td><td>4</td><td>4</td><td class="par">4</td><td>3</td><td class="birdie">3</td><td>3</td><td>N</td><td>3</td>
					</tr>
					<tr>
						<td>6</td><td>4</td><td>8</td><td class="dblbogey">8</td><td>-</td><td class="dblbogey">7</td><td>-</td><td>N</td><td>-</td>
					</tr>
					<tr>
						<td>7</td><td>5</td><td>18</td><td class="birdie">4</td><td>3</td><td class="birdie">4</td><td>3</td><td>Y</td><td>6</td>
					</tr>
					<tr>
						<td>8</td><td>3</td><td>16</td><td class="bogey">4</td><td>1</td><td class="par">3</td><td>2</td><td>N</td><td>2</td>
					</tr>
					<tr>
						<td>9</td><td>4</td><td>6</td><td class="bogey">5</td><td>1</td><td class="par">4</td><td>2</td><td>N</td><td>2</td>	
					</tr>
				</tbody>
			</table>
		</div> <!-- end scores div -->
	</div> <!-- end morning_tab div -->
	<div id="afternoon_tab">
		<div class="scores">
			<table class="player">
				<thead>
					<tr>
						<th>Competition</th>
						<th colspan="3">Player</th>
						<th class="courseinfo">Par</th>
						<th class="courseinfo">SSS</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td rowspan="2">Championship</td>
						<td rowspan="2">Phil Reeve</td>
						<td>Handicap</td>
						<td>17</td>
						<td rowspan="2" class="courseinfo">72</td>
						<td rowspan="2" class="courseinfo">70</td>
					</tr>
					<tr>
						<td>7/8ths</td>
						<td>15</td>
					</tr>
				</tbody>
			</table>
			<table class="pmscores">
				<caption>Afternoon Front Nine</caption>
				<colgroup class="holeinfo">
					<col />
					<col />
					<col />
				</colgroup>
				<colgroup class="scoreinfo">
					<col />
					<col />
					<col />
					<col />
				</colgroup>
				<thead>
					<tr>
						<th>Hole</th>
						<th>Par</th>
						<th>SI</th>
						<th>Gross Score</th>
						<th>Gross Points</th>
						<th>Net Score</th>
						<th>Net Points</th>
					</tr>
				</thead>
				<tfoot>
					<tr>
						<td>-</td><td>36</td><td>-</td><td>45 (+9)</td><td>11</td><td>39 (+3)</td><td>16</td>
					</tr>
				</tfoot>
				<tbody>
					<tr>
						<td>1</td><td>4</td><td>9</td><td class="bogey">5</td><td>1</td><td class="par">4</td><td>2</td>
					</tr>
					<tr>
						<td>2</td><td>4</td><td>11</td><td class="dblbogey">6</td><td>-</td><td class="bogey">5</td><td>1</td>
					</tr>
					<tr>
						<td>3</td><td>3</td><td>17</td><td class="bogey">4</td><td>1</td><td class="bogey">4</td><td>1</td>
					</tr>
					<tr>
						<td>4</td><td>5</td><td>3</td><td class="par">5</td><td>2</td><td class="birdie">4</td><td>3</td>
					</tr>
					<tr>
						<td>5</td><td>4</td><td>4</td><td class="par">4</td><td>2</td><td class="birdie">3</td><td>3</td>
					</tr>
					<tr>
						<td>6</td><td>4</td><td>8</td><td class="dblbogey">8</td><td>-</td><td class="dblbogey">7</td><td>-</td>
					</tr>
					<tr>
						<td>7</td><td>5</td><td>18</td><td class="birdie">4</td><td>3</td><td class="birdie">4</td><td>3</td>
					</tr>
					<tr>
						<td>8</td><td>3</td><td>16</td><td class="bogey">4</td><td>1</td><td class="bogey">4</td><td>1</td>
					</tr>
					<tr>
						<td>9</td><td>4</td><td>6</td><td class="bogey">5</td><td>1</td><td class="par">4</td><td>2</td>
					</tr>
				</tbody>
			</table>
			<table class="pmscores">
				<caption>Afternoon Back Nine</caption>
				<colgroup class="holeinfo">
					<col />
					<col />
					<col />
				</colgroup>
				<colgroup class="scoreinfo">
					<col />
					<col />
					<col />
					<col />
				</colgroup>
				<thead>
					<tr>
						<th>Hole</th>
						<th>Par</th>
						<th>SI</th>
						<th>Gross Score</th>
						<th>Gross Points</th>
						<th>Net Score</th>
						<th>Net Points</th>
					</tr>
				</thead>
				<tfoot>
					<tr>
						<td>-</td><td>36</td><td>-</td><td>45 (+9)</td><td>11</td><td>39 (+3)</td><td>16</td>
					</tr>
				</tfoot>
				<tbody>
					<tr>
						<td>1</td><td>4</td><td>9</td><td class="bogey">5</td><td>1</td><td class="par">4</td><td>2</td>
					</tr>
					<tr>
						<td>2</td><td>4</td><td>11</td><td class="dblbogey">6</td><td>-</td><td class="bogey">5</td><td>1</td>
					</tr>
					<tr>
						<td>3</td><td>3</td><td>17</td><td class="bogey">4</td><td>1</td><td class="bogey">4</td><td>1</td>
					</tr>
					<tr>
						<td>4</td><td>5</td><td>3</td><td class="par">5</td><td>2</td><td class="birdie">4</td><td>3</td>
					</tr>
					<tr>
						<td>5</td><td>4</td><td>4</td><td class="par">4</td><td>2</td><td class="birdie">3</td><td>3</td>
					</tr>
					<tr>
						<td>6</td><td>4</td><td>8</td><td class="dblbogey">8</td><td>-</td><td class="dblbogey">7</td><td>-</td>
					</tr>
					<tr>
						<td>7</td><td>5</td><td>18</td><td class="birdie">4</td><td>3</td><td class="birdie">4</td><td>3</td>
					</tr>
					<tr>
						<td>8</td><td>3</td><td>16</td><td class="bogey">4</td><td>1</td><td class="bogey">4</td><td>1</td>
					</tr>
					<tr>
						<td>9</td><td>4</td><td>6</td><td class="bogey">5</td><td>1</td><td class="par">4</td><td>2</td>
					</tr>
				</tbody>
			</table>
			<table class="pmscores">
				<caption>Afternoon Total</caption>
				<colgroup class="holeinfo">
					<col />
					<col />
					<col />
				</colgroup>
				<colgroup class="scoreinfo">
					<col />
					<col />
					<col />
					<col />
				</colgroup>
				<thead>
					<tr>
						<th>Hole</th>
						<th>Par</th>
						<th>SI</th>
						<th>Gross Score</th>
						<th>Gross Points</th>
						<th>Net Score</th>
						<th>Net Points</th>
					</tr>
				</thead>
				<tfoot>
					<tr>
						<td>-</td><td>72</td><td>-</td><td>90 (+18)</td><td>22</td><td>78 (+6)</td><td>32</td>
					</tr>
				</tfoot>
				<tbody>
					<tr>
						<td>Front</td><td>36</td><td>-</td><td>45</td><td>11</td><td>39</td><td>16</td>
					</tr>
					<tr>
						<td>Back</td><td>36</td><td>-</td><td>45</td><td>11</td><td>39</td><td>16</td>
					</tr>
				</tbody>
			</table>
		</div> <!-- end scores div -->
	</div> <!-- end afternoon_tab div -->
</div> <!-- end score_tabs div -->