<h2>Players</h2>
<p>Your current handicap, you'll have to check the <a href="index.php?pagetype=playerhistory">handicap history</a> to work out why it is what it is.</p>
<div class="player_info">
	<table class="player_table">
		<colgroup class="player">
			<col />
		</colgroup>
		<colgroup class="handicap">
			<col />
			<col />
		</colgroup>
		<thead>
			<tr>
				<th rowspan="2" class="player_name">Player</th>
				<th colspan="2">Current Handicap</th>
			</tr>
			<tr>
				<th>Morning</th>
				<th>Afternoon</th>
			</tr>
		</thead>
		<tfoot>
			<tr>
				<td colspan="3">Historical Handicaps can be found <a href="index.php?pagetype=playerhistory">here</a></td>
			</tr>
		</tfoot>
		<tbody>
			<tr>
				<td class="player_name">Phil Reeve</td>
				<td>15</td>
				<td>16</td>
			</tr>
			<tr>
				<td class="player_name">Mike Conroy</td>
				<td>11</td>
				<td>11</td>
			</tr>
			<tr>
				<td class="player_name">Liam Richards</td>
				<td>25</td>
				<td>24</td>
			</tr>
			<tr>
				<td class="player_name">Rob Ashton</td>
				<td>32</td>
				<td>29</td>
			</tr>
			<tr>
				<td class="player_name">Iain More</td>
				<td>10</td>
				<td>10</td>
			</tr>
			<tr>
				<td class="player_name">Gordon Neilson</td>
				<td>7</td>
				<td>4</td>
			</tr>
			<tr>
				<td class="player_name">Andy Wraight</td>
				<td>4</td>
				<td>5</td>
			</tr>
			<tr>
				<td class="player_name">Dave Roberts</td>
				<td>22</td>
				<td>20</td>
			</tr>
			<tr>
				<td class="player_name">Paul Wilson</td>
				<td>9</td>
				<td>9</td>
			</tr>
			<tr>
				<td class="player_name">Peter Blackman</td>
				<td>31</td>
				<td>30</td>
			</tr>
			<tr>
				<td class="player_name">Nigel Attwood</td>
				<td>14</td>
				<td>17</td>
			</tr>
			<tr>
				<td class="player_name">Pete McIntyre</td>
				<td>23</td>
				<td>21</td>
			</tr>
			<tr>
				<td class="player_name">Peter Hobin</td>
				<td>24</td>
				<td>24</td>
			</tr>
			<tr>
				<td class="player_name">Chris Locke</td>
				<td>22</td>
				<td>22</td>
			</tr>
			<tr>
				<td class="player_name">Morris Goulding</td>
				<td>24</td>
				<td>30</td>
			</tr>
			<tr>
				<td class="player_name">Dave Canderton</td>
				<td>15</td>
				<td>15</td>
			</tr>
			<tr>
				<td class="player_name">Duncan Clark</td>
				<td>18</td>
				<td>18</td>
			</tr>
			<tr>
				<td class="player_name">Jerry Spencer</td>
				<td>19</td>
				<td>19</td>
			</tr>
			<tr>
				<td class="player_name">Mark Andrews</td>
				<td>25</td>
				<td>25</td>
			</tr>
			<tr>
				<td class="player_name">Martin Curran</td>
				<td>25</td>
				<td>26</td>
			</tr>
			<tr>
				<td class="player_name">Mike Cave</td>
				<td>20</td>
				<td>20</td>
			</tr>
			<tr>
				<td class="player_name">Mike Capaldi</td>
				<td>13</td>
				<td>13</td>
			</tr>
			<tr>
				<td class="player_name">Steve Arrowsmith</td>
				<td>18</td>
				<td>18</td>
			</tr>
			<tr>
				<td class="player_name">Keith Strickland</td>
				<td>28</td>
				<td>28</td>
			</tr>
		</tbody>
	</table>
</div>