<div>
	<h2>Autumn 2010 Videos - Morning</h2>
	<p><a href="index.php?pagetype=videos&amp;season=autumn&amp;year=2010&amp;ampm=pm">Afternoon videos</a> also available</p>
	<div class="_videos">
		<h4 id="andy_wraight">Andy Wraight</h4>
		<p>Relaxed on the tee as always</p>
		<a href="http://www.youtube.com/embed/eu8uuR7o2F8?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2010/am/andy_wraight.jpg" alt="Andy Wraight" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="dave_roberts">Dave Roberts</h4>
		<p>A little rigid in the morning is our Dave</p>
		<a href="http://www.youtube.com/embed/UnzR_9Ojfik?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2010/am/dave_roberts.jpg" alt="Dave Roberts" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="gordon_neilson">Gordon Neilson</h4>
		<p>The unique and supremely effective stylings...</p>
		<a href="http://www.youtube.com/embed/wQEQ1dlw98g?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2010/am/gordon_neilson.jpg" alt="Gordon Neilson" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="iain_more">Iain More</h4>
		<p>Quick and smooth, like Mr Bond</p>
		<a href="http://www.youtube.com/embed/he9MQ8SIK50?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2010/am/iain_more.jpg" alt="Iain More" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="liam_richards">Liam Richards</h4>
		<p>No fuss, no nonsense, bang!</p>
		<a href="http://www.youtube.com/embed/G4_WNZa3L_E?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2010/am/liam_richards.jpg" alt="Liam Richards" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="martin_curran">Martin Curran</h4>
		<p>Simple, but was it effective?</p>
		<a href="http://www.youtube.com/embed/Dzkgaf8mGB0?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2010/am/martin_curran.jpg" alt="Martin Curran" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="mike_cave">Mike Cave</h4>
		<p>Look at those hips!</p>
		<a href="http://www.youtube.com/embed/Y-hhcPYF5LA?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2010/am/mike_cave.jpg" alt="Mike Cave" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="mike_conroy">Mike Conroy</h4>
		<p>Did he like it? Who can tell?</p>
		<a href="http://www.youtube.com/embed/wFxVmfXzPnk?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2010/am/mike_conroy.jpg" alt="Mike Conroy" title="Click to Play" height="192" width="144" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="nigel_attwood">Nigel Attwood</h4>
		<p>Reminiscent of Sandy Lyle's backswing there</p>
		<a href="http://www.youtube.com/embed/kAV65rP2wQ8?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2010/am/nigel_attwood.jpg" alt="Nigel Attwood" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="paul_wilson">Paul Wilson</h4>
		<p>Classic and simple</p>
		<a href="http://www.youtube.com/embed/ZoD1h8FOYSM?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2010/am/paul_wilson.jpg" alt="Paul Wilson" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="pete_mcintyre">Pete McIntyre</h4>
		<p>We think that one went a little to the left</p>
		<a href="http://www.youtube.com/embed/xbG2u1EgprM?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2010/am/pete_mcintyre.jpg" alt="Pete McIntyre" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="peter_blackman">Peter Blackman</h4>
		<p>A classic wedge shot with a 3 iron</p>
		<a href="http://www.youtube.com/embed/URqf_cqqBUA?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2010/am/peter_blackman.jpg" alt="Peter Blackman" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="phil_reeve">Phil Reeve</h4>
		<p>Slow back and Bam!</p>
		<a href="http://www.youtube.com/embed/3DhoCrd_-NQ?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2010/am/phil_reeve.jpg" alt="Phil Reeve" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="rob_ashton">Rob Ashton</h4>
		<p>I'm not sure that finish is what the pro taught you</p>
		<a href="http://www.youtube.com/embed/1GjF0q-1MnU?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2010/am/rob_ashton.jpg" alt="Rob Ashton" title="Click to Play" height="144" width="192" />
		</a>
	</div>
</div>