<div>
	<h2>Autumn 2010 Videos - Afternoon</h2>
	<p><a href="index.php?pagetype=videos&amp;season=autumn&amp;year=2010&amp;ampm=am">Morning videos</a> also available</p>
	<div class="_videos">
		<h4 id="iain_more">Iain More</h4>
		<p>On his way to victory!!</p>
		<a href="http://www.youtube.com/embed/boty9FF8Vsw?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2010/pm/iain_more.jpg" alt="Iain More" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="mike_conroy">Mike Conroy</h4>
		<p>???</p>
		<a href="http://www.youtube.com/embed/bKipQDCP3RQ?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2010/pm/mike_conroy.jpg" alt="Mike Conroy" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="nigel_attwood">Nigel Attwood</h4>
		<p>???</p>
		<a href="http://www.youtube.com/embed/Q1BKbt4DEJc?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2010/pm/nigel_attwood.jpg" alt="Nigel Attwood" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="rob_ashton">Rob Ashton</h4>
		<p>???</p>
		<a href="http://www.youtube.com/embed/5ET4D4XVs30?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 480, height: 640, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2010/pm/rob_ashton.jpg" alt="Rob Ashton" title="Click to Play" height="192" width="144" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="pete_mcintyre">Pete McIntyre</h4>
		<p>???</p>
		<a href="http://www.youtube.com/embed/AuCfhAdyqVo?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2010/pm/pete_mcintyre.jpg" alt="Pete McIntyre" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="gordon_neilson">Gordon Neilson</h4>
		<p>???</p>
		<a href="http://www.youtube.com/embed/zmUKMXVjjnY?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 480, height: 640, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2010/pm/gordon_neilson.jpg" alt="Gordon Neilson" title="Click to Play" height="192" width="144" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="peter_blackman">Peter Blackman</h4>
		<p>Where's this going to go?</p>
		<a href="http://www.youtube.com/embed/IwXrhtnp7iY?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 480, height: 640, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2010/pm/peter_blackman_1.jpg" alt="Peter Blackman" title="Click to Play" height="192" width="144" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="peter_blackman">Peter Blackman</h4>
		<p>Really? Over there?</p>
		<a href="http://www.youtube.com/embed/O2Qwub9p8Mo?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 480, height: 640, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2010/pm/peter_blackman_2.jpg" alt="Peter Blackman" title="Click to Play" height="192" width="144" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="peter_blackman">Peter Blackman</h4>
		<p>Let's have another go (iron this time!)</p>
		<a href="http://www.youtube.com/embed/1lwqiMFKqGM?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2010/pm/peter_blackman_3.jpg" alt="Peter Blackman" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="phil_reeve">Phil Reeve</h4>
		<p>???</p>
		<a href="http://www.youtube.com/embed/CsnJcURyYHw?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 480, height: 640, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2010/pm/phil_reeve.jpg" alt="Phil Reeve" title="Click to Play" height="192" width="144" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="dave_roberts">Dave Roberts</h4>
		<p>???</p>
		<a href="http://www.youtube.com/embed/g7Q7E1te6Fw?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 480, height: 640, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2010/pm/dave_roberts.jpg" alt="Dave Roberts" title="Click to Play" height="192" width="144" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="andy_wraight">Andy Wraight</h4>
		<p>???</p>
		<a href="http://www.youtube.com/embed/B5ySmSbUDmw?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2010/pm/andy_wraight.jpg" alt="Andy Wraight" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="liam_richards">Liam Richards</h4>
		<p>???</p>
		<a href="http://www.youtube.com/embed/3CB2wV0CNa4?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2010/pm/liam_richards.jpg" alt="Liam Richards" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="martin_curran">Martin Curran</h4>
		<p>???</p>
		<a href="http://www.youtube.com/embed/_doGrxvsVyA?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2010/pm/martin_curran.jpg" alt="Martin Curran" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="mike_cave">Mike Cave</h4>
		<p>Video Missing !!!</p>
		<!-- <a href="http://www.youtube.com/embed/3CB2wV0CNa4?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide"> -->
			<img src="media/videos/autumn_2010/pm/mike_cave.jpg" alt="Mike Cave" title="Click to Play" height="144" width="192" />
		<!-- </a> -->
	</div>
	<div class="_videos">
		<h4 id="paul_wilson">Paul Wilson</h4>
		<p>???</p>
		<a href="http://www.youtube.com/embed/XUwBxhbeAQc?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2010/pm/paul_wilson.jpg" alt="Paul Wilson" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="morris_goulding">Morris Goulding</h4>
		<p>???</p>
		<a href="http://www.youtube.com/embed/rLSGuM8zhBc?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2010/pm/morris_goulding.jpg" alt="Morris Goulding" title="Click to Play" height="144" width="192" />
		</a>
	</div>
</div>