<div>
	<h2>Autumn 2011 Videos - Morning</h2>
	<p><a href="index.php?pagetype=videos&amp;season=autumn&amp;year=2011&amp;ampm=am">Morning videos</a> also available</p>
	<div class="_videos">
		<h4 id="mike_conroy">Mike Conroy</h4>
		<p>???</p>
		<a href="http://www.youtube.com/embed/rPNWzMzSjpg?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2011/am/mike_conroy.jpg" alt="Mike Conroy" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="dave_roberts">Dave Roberts</h4>
		<p>???</p>
		<a href="http://www.youtube.com/embed/icL0O5bLGeA?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2011/am/dave_roberts.jpg" alt="Dave Roberts" title="Click to Play" height="141" width="187" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="chris_locke">Chris Locke</h4>
		<p>???</p>
		<a href="http://www.youtube.com/embed/CCDFzQB8kJQ?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2011/am/chris_locke.jpg" alt="Chris Locke" title="Click to Play" height="141" width="187" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="jerry_burton">Jerry Burton</h4>
		<p>???</p>
		<a href="http://www.youtube.com/embed/2-arORmDz1I?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2011/am/jerry_burton.jpg" alt="Jerry Burton" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="duncan_clark">Duncan Clark</h4>
		<p>???</p>
		<a href="http://www.youtube.com/embed/w0us5GWftvg?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2011/am/duncan_clark.jpg" alt="Duncan Clark" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="peter_blackman">Peter Blackman</h4>
		<p???</p>
		<a href="http://www.youtube.com/embed/mSVqUheSiWI?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2011/am/peter_blackman.jpg" alt="Peter Blackman" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="nigel_attwood">Nigel Attwood</h4>
		<p>???</p>
		<a href="http://www.youtube.com/embed/_JZ5CErtkcY?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2011/am/nigel_attwood.jpg" alt="Nigel Attwood" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="murray_scott">Murray Scott</h4>
		<p>???</p>
		<a href="http://www.youtube.com/embed/Pzp05A-Z5to?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2011/am/murray_scott.jpg" alt="Murray Scott" title="Click to Play" height="192" width="144" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="phil_reeve">Phil Reeve</h4>
		<p>???</p>
		<a href="http://www.youtube.com/embed/kWUI0AosWpo?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2011/am/phil_reeve.jpg" alt="Phil Reeve" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="rob_ashton">Rob Ashton</h4>
		<p>???</p>
		<a href="http://www.youtube.com/embed/UfF6jzR26Ns?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2011/am/rob_ashton.jpg" alt="Rob Ashton" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="paul_stevens">Paul Stevens</h4>
		<p>???</p>
		<a href="http://www.youtube.com/embed/OgfxT9r7P3g?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2011/am/paul_stevens.jpg" alt="Paul Stevens" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="barry_griffiths">Barry Griffiths</h4>
		<p>???</p>
		<a href="http://www.youtube.com/embed/mastllGRBOE?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2011/am/barry_griffiths.jpg" alt="Barry Griffiths" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="liam_richards">Liam Richards</h4>
		<p>???</p>
		<a href="http://www.youtube.com/embed/wAT9xMes4Ac?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2011/am/liam_richards.jpg" alt="Liam Richards" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="pete_mcintyre">Pete McIntyre</h4>
		<p>???</p>
		<a href="http://www.youtube.com/embed/YO7t89UyKac?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2011/am/pete_mcintyre.jpg" alt="Pete McIntyre" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="dave_davies">Dave Davies</h4>
		<p>???</p>
		<a href="http://www.youtube.com/embed/dFaJOyuGAbs?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/autumn_2011/am/dave_davies.jpg" alt="Dave Davies" title="Click to Play" height="144" width="192" />
		</a>
	</div>
</div>