<div>
	<h2>Spring 2011 Videos - Morning</h2>
	<p><a href="index.php?pagetype=videos&amp;season=spring&amp;year=2011&amp;ampm=pm">Afternoon videos</a> also available</p>
	<div class="_videos">
		<h4 id="mike_conroy">Mike Conroy</h4>
		<p>Ahhh, the endless wiggling!</p>
		<a href="http://www.youtube.com/embed/s9gitvy7kKs?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/spring_2011/am/mike_conroy.jpg" alt="Mike Conroy" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="andy_wraight">Andy Wraight</h4>
		<p>Hold, hold, swish, ping!</p>
		<a href="http://www.youtube.com/embed/ib3YR5mehlk?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/spring_2011/am/andy_wraight.jpg" alt="Andy Wraight" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="chris_locke">Chris Locke</h4>
		<p>Slow, simple and effective</p>
		<a href="http://www.youtube.com/embed/HGiLT9WSqwk?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/spring_2011/am/chris_locke.jpg" alt="Chris Locke" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="dave_roberts">Dave Roberts</h4>
		<p>It all looked so good but the tilt of the head said different</p>
		<a href="http://www.youtube.com/embed/e-_IkY99b7g?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/spring_2011/am/dave_roberts.jpg" alt="Dave Roberts" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="gordon_neilson">Gordon Neilson</h4>
		<p>The cock of the head said worried, but we all know the result</p>
		<a href="http://www.youtube.com/embed/9L9gS6NKB3g?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/spring_2011/am/gordon_neilson.jpg" alt="Gordon Neilson" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="iain_more">Iain More</h4>
		<p>The backswing is faster than the downswing, good result no doubt</p>
		<a href="http://www.youtube.com/embed/GtDKuNjMW1g?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/spring_2011/am/iain_more.jpg" alt="Iain More" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="liam_richards">Liam Richards</h4>
		<p>Liam's little knee wiggle to the fore once more</p>
		<a href="http://www.youtube.com/embed/NoBrUEKIFHs?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/spring_2011/am/liam_richards.jpg" alt="Liam Richards" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="pete_mcintyre">Pete McIntyre</h4>
		<p>The crowd liked it</p>
		<a href="http://www.youtube.com/embed/wOyNBUYn_jg?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/spring_2011/am/pete_mcintyre.jpg" alt="Pete McIntyre" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="peter_blackman">Peter Blackman</h4>
		<p>Peter avoids the car park this year</p>
		<a href="http://www.youtube.com/embed/OHoaUabMhQM?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/spring_2011/am/peter_blackman.jpg" alt="Peter Blackman" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="phil_reeve">Phil Reeve</h4>
		<p>That got a thwack and good murmurs from the crowd</p>
		<a href="http://www.youtube.com/embed/zCI_fVsQ0P0?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/spring_2011/am/phil_reeve.jpg" alt="Phil Reeve" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="rob_ashton">Rob Ashton</h4>
		<p>Hmmm, I guess he's hoping he gets past the ladies tee</p>
		<a href="http://www.youtube.com/embed/rrCchex77Kc?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/spring_2011/am/rob_ashton.jpg" alt="Rob Ashton" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="rob_ladies">Rob on the Ladies Tee</h4>
		<p>Only Just!</p>
		<a href="http://www.youtube.com/embed/5dSIvj0PPmo?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/spring_2011/am/rob_ladies.jpg" alt="Rob on the Ladies Tee" title="Click to Play" height="144" width="192" />
		</a>
	</div>
</div>