<div>
	<h2>Spring 2011 Videos - Afternoon</h2>
	<p>Have we got any better than we were in <a href="index.php?pagetype=videos&amp;season=spring&amp;year=2011&amp;ampm=am">the morning?</a></p>
	<div class="_videos">
		<h4 id="mike_conroy">Mike Conroy</h4>
		<p>???</p>
		<a href="http://www.youtube.com/embed/LlJ-Glsf0EM?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/spring_2011/pm/mike_conroy.jpg" alt="Mike Conroy" title="Click to Play" height="192" width="144" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="gordon_neilson">Gordon Neilson</h4>
		<p>???</p>
		<a href="http://www.youtube.com/embed/_7xj4KTm1ik?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/spring_2011/pm/gordon_neilson.jpg" alt="Gordon Neilson" title="Click to Play" height="192" width="144" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="andy_wraight">Andy Wraight</h4>
		<p>???</p>
		<a href="http://www.youtube.com/embed/BhHvDdpLiOE?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/spring_2011/pm/andy_wraight.jpg" alt="Andy Wraight" title="Click to Play" height="192" width="144" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="phil_reeve">Phil Reeve</h4>
		<p>???</p>
		<a href="http://www.youtube.com/embed/=msL11_RWs-I?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/spring_2011/pm/phil_reeve.jpg" alt="Phil Reeve" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="iain_more">Iain More</h4>
		<p>???</p>
		<a href="http://www.youtube.com/embed/PR6-EwQdtrs?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/spring_2011/pm/iain_more.jpg" alt="Iain More" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="pete_mcintyre">Pete McIntyre</h4>
		<p>???</p>
		<a href="http://www.youtube.com/embed/S7bmJYWEHM4?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/spring_2011/pm/pete_mcintyre.jpg" alt="Pete McIntyre" title="Click to Play" height="145" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="liam_richards">Liam Richards</h4>
		<p>???</p>
		<a href="http://www.youtube.com/embed/t2uJzTWKi3E?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/spring_2011/pm/liam_richards.jpg" alt="Liam Richards" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="peter_blackman">Peter Blackman</h4>
		<p>???</p>
		<a href="http://www.youtube.com/embed/EF9xivAM8GQE?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/spring_2011/pm/peter_blackman.jpg" alt="Peter Blackman" title="Click to Play" height="145" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="chris_locke">Chris Locke</h4>
		<p>???</p>
		<a href="http://www.youtube.com/embed/fDTHzbjnMQc?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/spring_2011/pm/chris_locke.jpg" alt="Chris Locke" title="Click to Play" height="145" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="rob_ashton">Rob Ashton</h4>
		<p>???</p>
		<a href="http://www.youtube.com/embed/OleBa6JLUXk?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/spring_2011/pm/rob_ashton.jpg" alt="Rob Ashton" title="Click to Play" height="144" width="192" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="dave_roberts">Dave Roberts</h4>
		<p>???</p>
		<a href="http://www.youtube.com/embed/cUDezU52M8U?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/spring_2011/pm/dave_roberts.jpg" alt="Dave Roberts" title="Click to Play" height="143" width="191" />
		</a>
	</div>
	<div class="_videos">
		<h4 id="morris_goulding">Morris Goulding</h4>
		<p>???</p>
		<a href="http://www.youtube.com/embed/LabylXMQeIg?rel=0&amp;wmode=transparent&amp;autoplay=1&amp;modestbranding=1" onclick="return hs.htmlExpand(this, {objectType: 'iframe', width: 640, height: 480, allowSizeReduction: false, wrapperClassName: 'draggable-header no-footer', preserveContent: false, objectLoadTime: 'after'})" class="highslide">
			<img src="media/videos/spring_2011/pm/morris_goulding.jpg" alt="Morris Goulding" title="Click to Play" height="144" width="192" />
		</a>
	</div>
</div>