<div id="newsflash" class="newsflash">
	<div class="spacing">
		<div class="storyimage">
			<a href="media/images/burhill_big.jpg" class="highslide" onclick="return hs.expand(this)">
				<img src="media/images/burhill_small.jpg" alt="Burhill" title="Click to enlarge" height="286" width="429" />
			</a>
		</div>
		<div class="highslide-caption">
			Burhill Golf Club
		</div>
		<h2>Autumn 2011 - Burhill Golf Club</h2>
		<p><a href="http://www.burhillgolf-club.co.uk/">Burhill Golf Club</a> has been confirmed for the 14th October! Book early to avoid disappointment!</p>
		<p>You better get down to the practice range, book some lessons with your friendly pro and generally get yourselves ready for this one, it's going to be a great day out but expect to be challenged.</p>
		<p>Look forward to seeing you there.</p>
		<p>Mike<a class="readmore" href="index.php?pagetype=planning&amp;season=autumn&amp;year=2011">Read More &gt;&gt;</a></p>
	</div> <!-- end spacing -->
</div> <!-- end newsflash -->