<div id="namequestion" class="full_item">
	<div class="spacing">
		<h2>We need a better name...</h2>
		<p>OK, I can't help but feel that <span style="font-style:italic;">Alternative Golf Day Society</span> lacks a certain pithy humour or perhaps a tongue in cheek poke at something we all recognise. Anywho, if you have any ideas then shout!</p>
		<p>So far all I've been able to come up with are the following, there must be something better?</p>
		<ul>
			<li>Furtive Elven Men Gain Tanning Oil (an anagram)</li>
			<li>Lazy Elves Golfing Society</li>
		</ul>
		<p>Mike</p>
	</div> <!-- end spacing -->
</div> <!-- end full item -->