<script type="text/javascript" src="javascripts/highslide/highslide-with-html.js"></script>
<script type="text/javascript">
    // Apply the Highslide settings
    hs.graphicsDir = 'media/images/highslide/';
	hs.align = 'center';
	hs.transitions = ['expand', 'crossfade'];
	hs.fadeInOut = true;
	hs.dimmingOpacity = 1;
    hs.outlineType = 'rounded-white';
    hs.outlineWhileAnimating = true;
</script>