<h2>Videos Menu</h2>
<div class="leftmenu">
	<ul>
		<li><a href="index.php?pagetype=videos&amp;season=autumn&amp;year=2011&amp;ampm=am">Autumn 2011</a>
			<ul>
				<li><a href="index.php?pagetype=videos&amp;season=autumn&amp;year=2011&amp;ampm=am">Morning</a></li>
				<li><a href="index.php?pagetype=videos&amp;season=autumn&amp;year=2011&amp;ampm=pm">Afternoon</a></li>
			</ul>
		</li>
		<li><a href="index.php?pagetype=videos&amp;season=spring&amp;year=2011&amp;ampm=am">Spring 2011</a>
			<ul>
				<li><a href="index.php?pagetype=videos&amp;season=spring&amp;year=2011&amp;ampm=am">Morning</a></li>
				<li><a href="index.php?pagetype=videos&amp;season=spring&amp;year=2011&amp;ampm=pm">Afternoon</a></li>
			</ul>
		</li>
		<li><a href="index.php?pagetype=videos&amp;season=autumn&amp;year=2010&amp;ampm=am">Autumn 2010</a>
			<ul>
				<li><a href="index.php?pagetype=videos&amp;season=autumn&amp;year=2010&amp;ampm=am">Morning</a></li>
				<li><a href="index.php?pagetype=videos&amp;season=autumn&amp;year=2010&amp;ampm=pm">Afternoon</a></li>
			</ul>
		</li>
		<li><a href="index.php?pagetype=videos&amp;season=spring&amp;year=2010">Spring 2010</a></li>
		<li><a href="index.php?pagetype=videos&amp;season=autumn&amp;year=2009">Autumn 2009</a></li>
		<li><a href="index.php?pagetype=videos&amp;season=spring&amp;year=2009">Spring 2009</a></li>
	</ul>
</div> <!-- end leftmenu -->