<h2>Photos Menu</h2>
<div class="leftmenu">
	<ul>
		<li><a href="index.php?pagetype=photos&amp;season=autumn&amp;year=2011">Autumn 2011</a></li>
		<li><a href="index.php?pagetype=photos&amp;season=spring&amp;year=2011">Spring 2011</a></li>
		<li><a href="index.php?pagetype=photos&amp;season=autumn&amp;year=2010">Autumn 2010</a></li>
		<li><a href="index.php?pagetype=photos&amp;season=spring&amp;year=2010">Spring 2010</a></li>
		<li><a href="index.php?pagetype=photos&amp;season=autumn&amp;year=2009">Autumn 2009</a></li>
		<li><a href="index.php?pagetype=photos&amp;season=spring&amp;year=2009">Spring 2009</a></li>
	</ul>
</div> <!-- end leftmenu -->