<div id="topnavbar">
	<div class="menu">
		<ul>
			<li><a class="left_nosub" href="index.php">Home</a></li>
			<li><a class="center_nosub" href="index.php?pagetype=results">Results</a></li>
			<li><a class="center_nosub" href="index.php?pagetype=scores">Scores</a></li>
			<li><a class="center_nosub" href="index.php?pagetype=photos">Photos</a></li>
			<li><a class="center_nosub" href="index.php?pagetype=videos">Videos</a></li>
			<li><a class="center_nosub" href="index.php?pagetype=winners">Winners</a></li>
			<li><a class="center_nosub" href="index.php?pagetype=players">Players</a></li>
			<li><a class="center_nosub" href="index.php?pagetype=history">History</a></li>
			<li><a class="right_nosub" href="index.php?pagetype=contact">Contact</a></li>
		</ul>
	</div>
</div>