<div class="resultssummary">
	<div class="storyimage">
		<a href="media/images/burhill_big.jpg" class="highslide" onclick="return hs.expand(this)">
			<img src="media/images/burhill_small.jpg" alt="Burhill" title="Click to enlarge" height="286" width="429" />
		</a>
	</div>
	<h2>Autumn 2011 Plans</h2>
	<p>The Autumn 2011 event will be held at <a href="http://www.burhillgolf-club.co.uk/">Burhill Golf Club</a> on the Friday 14th October.</p>
	<p>The usual arrangements with the exception that we will not be having dinner in the clubhouse afterwards, so breakfast (coffee and bacon rolls) 9 holes in the morning, lunch followed by the main event, 18 holes in the afternoon.</p>
	<p>The cost is £70 and we will have between 12 and 16 players.</p>
	<p>We may organise dinner at a local hostelry or restaurant (maybe an Indian) afterwards, depending on feedback, so don't hesitate to let us know.</p>
	<h3>What Next?</h3>
	<p>Make sure you get your money to Phil Reeve asap, book the day off work and get some practice in - this won't be the easiest course we've played at!</p>
	<p>If you have any special dietary requirements then let Mike know asap. There's a map you can use to get directions to the course below, scroll down a bit.</p>
	<h3>Details, details, details</h3>
	<p>The day kicks off at 8:00 am. No, I am not telling you when the first tee time is because half the folk will turn up at the last minute and I don't need the hassle and grief of wondering if and when you're going to show up. Nor have we finalised the groups, the only thing we do know is that they will be the same groups morning and afternoon, since we have a reasonably quick turnaround for lunch then first out in the morning will also be first out in the afernoon.</p>
	<ul>
		<li>Meet in the Honours bar for breakfast at 8:00am</li>
		<li>The morning 9 will be played on the new course, holes 10 to 18
			<ul>
				<li>Team yellow ball competition</li>
				<li>Blind pairs, to be drawn in the bar at the end of the day</li>
			</ul>
		</li>
		<li>The afternoon 18 will be played over the old course
			<ul>
				<li>Nearest the pin will be on the 6th</li>
				<li>Longest drive will be on the 15th</li>
			</ul>
		</li>
		<li>And of course the wooden spoon...</li>
	</ul>
	<h3>Beware the M25</h3>
	<p>The M25, as you all know, is notoriously busy around the M4, M3 and Heathrow every day, it won't come as a surprise, so leave yourself plenty of time to get there. We won't be waiting.</p>
	<h3>Getting There</h3>
	<div class="googlemap">
		<p>The map below shows where Burhill is and you can use this to find your own route there.</p>
		<p>A <a href="http://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=Burhill+Golf+Club,+Walton-on-Thames,+United+Kingdom&amp;aq=0&amp;sll=40.742055,-73.975067&amp;sspn=0.737694,1.783905&amp;vpsrc=6&amp;ie=UTF8&amp;hq=Burhill+Golf+Club,&amp;hnear=Walton-on-Thames,+United+Kingdom&amp;t=m&amp;ll=51.366851,-0.465202&amp;spn=0.102887,0.219727&amp;z=12" style="text-align:left">larger map</a> is available.</p>
		<iframe width="640" height="480" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Burhill+Golf+Club,+Walton-on-Thames,+United+Kingdom&amp;aq=0&amp;sll=40.742055,-73.975067&amp;sspn=0.737694,1.783905&amp;vpsrc=6&amp;ie=UTF8&amp;hq=Burhill+Golf+Club,&amp;hnear=Walton-on-Thames,+United+Kingdom&amp;t=m&amp;ll=51.366851,-0.465202&amp;spn=0.102887,0.219727&amp;z=12&amp;output=embed">
		</iframe>
		<br />
	</div>
	<br /><hr />
</div> <!--end resultssummary -->