<div class="resultssummary">
	<div class="storyimage">
			<a href="media/images/donnington_large.jpg" class="highslide" onclick="return hs.expand(this)">
				<img src="media/images/donnington_small.jpg" alt="Donnington" title="Click to enlarge" height="240" width="300" />
			</a>
		</div>
		<div class="highslide-caption">
			Burhill Golf Club
		</div>
		<h2>Spring 2012 - Donnington Grove Golf Club</h2>
		<p><a href="http://www.donnington-grove.com/categories/Golf/">Donnington Grove Golf Club</a> has been confirmed for the 13th June!</p>
		<p>You better get down to the practice range, book some lessons with your friendly pro and generally get yourselves ready for this one, it's going to be a great day out but expect to be challenged.</p>
		<p>Look forward to seeing you there.</p>
	<br /><hr />
</div> <!--end resultssummary -->